// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_UnKnown_0 Gender = 0
	Gender_Woman     Gender = 1
	Gender_Man       Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "UnKnown_0",
		1: "Woman",
		2: "Man",
	}
	Gender_value = map[string]int32{
		"UnKnown_0": 0,
		"Woman":     1,
		"Man":       2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type State int32

const (
	State_UnKnown_1 State = 0
	State_Disable   State = 1
	State_Enable    State = 2
	State_LogOffing State = 3
	State_LogOffed  State = 4
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "UnKnown_1",
		1: "Disable",
		2: "Enable",
		3: "LogOffing",
		4: "LogOffed",
	}
	State_value = map[string]int32{
		"UnKnown_1": 0,
		"Disable":   1,
		"Enable":    2,
		"LogOffing": 3,
		"LogOffed":  4,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type Bind int32

const (
	Bind_UnKnown_2 Bind = 0
	Bind_Unbound   Bind = 1
	Bind_Binding   Bind = 2
)

// Enum value maps for Bind.
var (
	Bind_name = map[int32]string{
		0: "UnKnown_2",
		1: "Unbound",
		2: "Binding",
	}
	Bind_value = map[string]int32{
		"UnKnown_2": 0,
		"Unbound":   1,
		"Binding":   2,
	}
)

func (x Bind) Enum() *Bind {
	p := new(Bind)
	*p = x
	return p
}

func (x Bind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Bind) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (Bind) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x Bind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Bind.Descriptor instead.
func (Bind) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type SignupWay int32

const (
	SignupWay_UnKnown_3   SignupWay = 0
	SignupWay_Username    SignupWay = 1
	SignupWay_PhoneNumber SignupWay = 2
	SignupWay_Email       SignupWay = 3
)

// Enum value maps for SignupWay.
var (
	SignupWay_name = map[int32]string{
		0: "UnKnown_3",
		1: "Username",
		2: "PhoneNumber",
		3: "Email",
	}
	SignupWay_value = map[string]int32{
		"UnKnown_3":   0,
		"Username":    1,
		"PhoneNumber": 2,
		"Email":       3,
	}
)

func (x SignupWay) Enum() *SignupWay {
	p := new(SignupWay)
	*p = x
	return p
}

func (x SignupWay) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignupWay) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (SignupWay) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x SignupWay) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignupWay.Descriptor instead.
func (SignupWay) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

type Platform int32

const (
	Platform_UnKnown_4 Platform = 0
	Platform_Web       Platform = 1
	Platform_Ios       Platform = 2
	Platform_Android   Platform = 3
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "UnKnown_4",
		1: "Web",
		2: "Ios",
		3: "Android",
	}
	Platform_value = map[string]int32{
		"UnKnown_4": 0,
		"Web":       1,
		"Ios":       2,
		"Android":   3,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[4].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[4]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

type Vip int32

const (
	Vip_UnKnown_5 Vip = 0
	Vip_NoVip     Vip = 1
	Vip_IsVip     Vip = 2
)

// Enum value maps for Vip.
var (
	Vip_name = map[int32]string{
		0: "UnKnown_5",
		1: "NoVip",
		2: "IsVip",
	}
	Vip_value = map[string]int32{
		"UnKnown_5": 0,
		"NoVip":     1,
		"IsVip":     2,
	}
)

func (x Vip) Enum() *Vip {
	p := new(Vip)
	*p = x
	return p
}

func (x Vip) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vip) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[5].Descriptor()
}

func (Vip) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[5]
}

func (x Vip) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vip.Descriptor instead.
func (Vip) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

type OAuthType int32

const (
	OAuthType_UnKnown_6 OAuthType = 0
	OAuthType_WeChat    OAuthType = 1
	OAuthType_GitHub    OAuthType = 2
	OAuthType_Google    OAuthType = 3
	OAuthType_Weibo     OAuthType = 4
	OAuthType_QQ        OAuthType = 5
)

// Enum value maps for OAuthType.
var (
	OAuthType_name = map[int32]string{
		0: "UnKnown_6",
		1: "WeChat",
		2: "GitHub",
		3: "Google",
		4: "Weibo",
		5: "QQ",
	}
	OAuthType_value = map[string]int32{
		"UnKnown_6": 0,
		"WeChat":    1,
		"GitHub":    2,
		"Google":    3,
		"Weibo":     4,
		"QQ":        5,
	}
)

func (x OAuthType) Enum() *OAuthType {
	p := new(OAuthType)
	*p = x
	return p
}

func (x OAuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OAuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[6].Descriptor()
}

func (OAuthType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[6]
}

func (x OAuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OAuthType.Descriptor instead.
func (OAuthType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

type PushType int32

const (
	PushType_UnKnown_7 PushType = 0 // 未知
	PushType_Single    PushType = 1 // 单聊
	PushType_Room      PushType = 2 // 房间
	PushType_Broadcast PushType = 3 // 广播
)

// Enum value maps for PushType.
var (
	PushType_name = map[int32]string{
		0: "UnKnown_7",
		1: "Single",
		2: "Room",
		3: "Broadcast",
	}
	PushType_value = map[string]int32{
		"UnKnown_7": 0,
		"Single":    1,
		"Room":      2,
		"Broadcast": 3,
	}
)

func (x PushType) Enum() *PushType {
	p := new(PushType)
	*p = x
	return p
}

func (x PushType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[7].Descriptor()
}

func (PushType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[7]
}

func (x PushType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushType.Descriptor instead.
func (PushType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

type Message int32

const (
	Message_UnKnown_8      Message = 0
	Message_HeartBeat      Message = 1
	Message_HeartBeatReply Message = 2
	Message_System         Message = 3
	Message_User           Message = 4
)

// Enum value maps for Message.
var (
	Message_name = map[int32]string{
		0: "UnKnown_8",
		1: "HeartBeat",
		2: "HeartBeatReply",
		3: "System",
		4: "User",
	}
	Message_value = map[string]int32{
		"UnKnown_8":      0,
		"HeartBeat":      1,
		"HeartBeatReply": 2,
		"System":         3,
		"User":           4,
	}
)

func (x Message) Enum() *Message {
	p := new(Message)
	*p = x
	return p
}

func (x Message) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[8].Descriptor()
}

func (Message) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[8]
}

func (x Message) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message.Descriptor instead.
func (Message) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

type OP int32

const (
	OP_UnKnown_9 OP = 0
	OP_REQ       OP = 1 // 请求消息, 主动请求
	OP_ACK       OP = 2 // 确认消息, 被动应答
	OP_NOTIFY    OP = 3 // 服务端主动通知消息
)

// Enum value maps for OP.
var (
	OP_name = map[int32]string{
		0: "UnKnown_9",
		1: "REQ",
		2: "ACK",
		3: "NOTIFY",
	}
	OP_value = map[string]int32{
		"UnKnown_9": 0,
		"REQ":       1,
		"ACK":       2,
		"NOTIFY":    3,
	}
)

func (x OP) Enum() *OP {
	p := new(OP)
	*p = x
	return p
}

func (x OP) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OP) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[9].Descriptor()
}

func (OP) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[9]
}

func (x OP) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OP.Descriptor instead.
func (OP) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x2b, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x0d, 0x0a, 0x09, 0x55, 0x6e, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x30, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x57, 0x6f, 0x6d, 0x61, 0x6e, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x61,
	0x6e, 0x10, 0x02, 0x2a, 0x4c, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x0a, 0x09,
	0x55, 0x6e, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x31, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x44,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x4f, 0x66, 0x66, 0x69, 0x6e,
	0x67, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x4f, 0x66, 0x66, 0x65, 0x64, 0x10,
	0x04, 0x2a, 0x2f, 0x0a, 0x04, 0x42, 0x69, 0x6e, 0x64, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x6e, 0x4b,
	0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x32, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x62, 0x6f,
	0x75, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x10, 0x02, 0x2a, 0x44, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x57, 0x61, 0x79, 0x12,
	0x0d, 0x0a, 0x09, 0x55, 0x6e, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x33, 0x10, 0x00, 0x12, 0x0c,
	0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x10, 0x02, 0x12, 0x09, 0x0a,
	0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x10, 0x03, 0x2a, 0x38, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x6e, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f,
	0x34, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x65, 0x62, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03,
	0x49, 0x6f, 0x73, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64,
	0x10, 0x03, 0x2a, 0x2a, 0x0a, 0x03, 0x56, 0x69, 0x70, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x6e, 0x4b,
	0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x35, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x6f, 0x56, 0x69,
	0x70, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x73, 0x56, 0x69, 0x70, 0x10, 0x02, 0x2a, 0x51,
	0x0a, 0x09, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x55,
	0x6e, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x36, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x65,
	0x43, 0x68, 0x61, 0x74, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x69, 0x74, 0x48, 0x75, 0x62,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x10, 0x03, 0x12, 0x09,
	0x0a, 0x05, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x51, 0x51, 0x10,
	0x05, 0x2a, 0x3e, 0x0a, 0x08, 0x50, 0x75, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a,
	0x09, 0x55, 0x6e, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x37, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d,
	0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x10,
	0x03, 0x2a, 0x51, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0d, 0x0a, 0x09,
	0x55, 0x6e, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x38, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x73,
	0x65, 0x72, 0x10, 0x04, 0x2a, 0x31, 0x0a, 0x02, 0x4f, 0x50, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x6e,
	0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x39, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x45, 0x51,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x43, 0x4b, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4e,
	0x4f, 0x54, 0x49, 0x46, 0x59, 0x10, 0x03, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x64, 0x2d, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x48, 0x69,
	0x73, 0x73, 0x73, 0x73, 0x73, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_common_proto_goTypes = []interface{}{
	(Gender)(0),    // 0: common.Gender
	(State)(0),     // 1: common.State
	(Bind)(0),      // 2: common.Bind
	(SignupWay)(0), // 3: common.SignupWay
	(Platform)(0),  // 4: common.Platform
	(Vip)(0),       // 5: common.Vip
	(OAuthType)(0), // 6: common.OAuthType
	(PushType)(0),  // 7: common.PushType
	(Message)(0),   // 8: common.Message
	(OP)(0),        // 9: common.OP
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      10,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
