// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: connect.proto

package connect

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PushMessageClient is the client API for PushMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushMessageClient interface {
	Push(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageReply, error)
}

type pushMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewPushMessageClient(cc grpc.ClientConnInterface) PushMessageClient {
	return &pushMessageClient{cc}
}

func (c *pushMessageClient) Push(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageReply, error) {
	out := new(MessageReply)
	err := c.cc.Invoke(ctx, "/connect.PushMessage/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushMessageServer is the server API for PushMessage service.
// All implementations must embed UnimplementedPushMessageServer
// for forward compatibility
type PushMessageServer interface {
	Push(context.Context, *Message) (*MessageReply, error)
	mustEmbedUnimplementedPushMessageServer()
}

// UnimplementedPushMessageServer must be embedded to have forward compatible implementations.
type UnimplementedPushMessageServer struct {
}

func (UnimplementedPushMessageServer) Push(context.Context, *Message) (*MessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedPushMessageServer) mustEmbedUnimplementedPushMessageServer() {}

// UnsafePushMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushMessageServer will
// result in compilation errors.
type UnsafePushMessageServer interface {
	mustEmbedUnimplementedPushMessageServer()
}

func RegisterPushMessageServer(s grpc.ServiceRegistrar, srv PushMessageServer) {
	s.RegisterService(&PushMessage_ServiceDesc, srv)
}

func _PushMessage_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMessageServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect.PushMessage/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMessageServer).Push(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// PushMessage_ServiceDesc is the grpc.ServiceDesc for PushMessage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushMessage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connect.PushMessage",
	HandlerType: (*PushMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _PushMessage_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connect.proto",
}
