// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: types/chat.proto

package chat

import (
	common "github.com/cd-home/Hissssss/api/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From int64           `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`                      // 发送者
	To   int64           `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`                          // 接收者
	Room int64           `protobuf:"varint,3,opt,name=room,proto3" json:"room,omitempty"`                      // 房间接收
	Body string          `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                       // 消息体
	Type common.PushType `protobuf:"varint,5,opt,name=type,proto3,enum=common.PushType" json:"type,omitempty"` // 发送类型
	Sub  common.Message  `protobuf:"varint,6,opt,name=sub,proto3,enum=common.Message" json:"sub,omitempty"`    // 发送子类型
	Op   common.OP       `protobuf:"varint,7,opt,name=op,proto3,enum=common.OP" json:"op,omitempty"`           // 操作类型
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_types_chat_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *SendMessageRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *SendMessageRequest) GetRoom() int64 {
	if x != nil {
		return x.Room
	}
	return 0
}

func (x *SendMessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendMessageRequest) GetType() common.PushType {
	if x != nil {
		return x.Type
	}
	return common.PushType(0)
}

func (x *SendMessageRequest) GetSub() common.Message {
	if x != nil {
		return x.Sub
	}
	return common.Message(0)
}

func (x *SendMessageRequest) GetOp() common.OP {
	if x != nil {
		return x.Op
	}
	return common.OP(0)
}

type SendMessageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int64     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	MsgId int64     `protobuf:"varint,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Op    common.OP `protobuf:"varint,4,opt,name=op,proto3,enum=common.OP" json:"op,omitempty"`
}

func (x *SendMessageReply) Reset() {
	*x = SendMessageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReply) ProtoMessage() {}

func (x *SendMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_types_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReply.ProtoReflect.Descriptor instead.
func (*SendMessageReply) Descriptor() ([]byte, []int) {
	return file_types_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendMessageReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendMessageReply) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *SendMessageReply) GetOp() common.OP {
	if x != nil {
		return x.Op
	}
	return common.OP(0)
}

// Message To Rabbitmq
type MessageToMQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId  int64           `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`                    // 消息序号
	Server string          `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`                   // 服务器
	Room   int64           `protobuf:"varint,3,opt,name=room,proto3" json:"room,omitempty"`                      // 房间号
	From   int64           `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`                      // 发送者
	To     int64           `protobuf:"varint,5,opt,name=to,proto3" json:"to,omitempty"`                          // 接收者
	Body   string          `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`                       // 消息体
	Type   common.PushType `protobuf:"varint,7,opt,name=type,proto3,enum=common.PushType" json:"type,omitempty"` // 发送类型
	Sub    common.Message  `protobuf:"varint,8,opt,name=sub,proto3,enum=common.Message" json:"sub,omitempty"`    // 发送子类型
	Op     common.OP       `protobuf:"varint,9,opt,name=op,proto3,enum=common.OP" json:"op,omitempty"`           // 操作类型
}

func (x *MessageToMQ) Reset() {
	*x = MessageToMQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageToMQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageToMQ) ProtoMessage() {}

func (x *MessageToMQ) ProtoReflect() protoreflect.Message {
	mi := &file_types_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageToMQ.ProtoReflect.Descriptor instead.
func (*MessageToMQ) Descriptor() ([]byte, []int) {
	return file_types_chat_proto_rawDescGZIP(), []int{2}
}

func (x *MessageToMQ) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessageToMQ) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *MessageToMQ) GetRoom() int64 {
	if x != nil {
		return x.Room
	}
	return 0
}

func (x *MessageToMQ) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *MessageToMQ) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *MessageToMQ) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MessageToMQ) GetType() common.PushType {
	if x != nil {
		return x.Type
	}
	return common.PushType(0)
}

func (x *MessageToMQ) GetSub() common.Message {
	if x != nil {
		return x.Sub
	}
	return common.Message(0)
}

func (x *MessageToMQ) GetOp() common.OP {
	if x != nil {
		return x.Op
	}
	return common.OP(0)
}

var File_types_chat_proto protoreflect.FileDescriptor

var file_types_chat_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x63, 0x68, 0x61, 0x74, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x21, 0x0a, 0x03, 0x73, 0x75, 0x62, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x73,
	0x75, 0x62, 0x12, 0x1a, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4f, 0x50, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x6a,
	0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x02, 0x6f, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x4f, 0x50, 0x52, 0x02, 0x6f, 0x70, 0x22, 0xec, 0x01, 0x0a, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x4d, 0x51, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73,
	0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x75, 0x73, 0x68,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x73, 0x75,
	0x62, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x73, 0x75, 0x62, 0x12, 0x1a, 0x0a,
	0x02, 0x6f, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x4f, 0x50, 0x52, 0x02, 0x6f, 0x70, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2e, 0x2f,
	0x70, 0x62, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_chat_proto_rawDescOnce sync.Once
	file_types_chat_proto_rawDescData = file_types_chat_proto_rawDesc
)

func file_types_chat_proto_rawDescGZIP() []byte {
	file_types_chat_proto_rawDescOnce.Do(func() {
		file_types_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_chat_proto_rawDescData)
	})
	return file_types_chat_proto_rawDescData
}

var file_types_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_types_chat_proto_goTypes = []interface{}{
	(*SendMessageRequest)(nil), // 0: chat.SendMessageRequest
	(*SendMessageReply)(nil),   // 1: chat.SendMessageReply
	(*MessageToMQ)(nil),        // 2: chat.MessageToMQ
	(common.PushType)(0),       // 3: common.PushType
	(common.Message)(0),        // 4: common.Message
	(common.OP)(0),             // 5: common.OP
}
var file_types_chat_proto_depIdxs = []int32{
	3, // 0: chat.SendMessageRequest.type:type_name -> common.PushType
	4, // 1: chat.SendMessageRequest.sub:type_name -> common.Message
	5, // 2: chat.SendMessageRequest.op:type_name -> common.OP
	5, // 3: chat.SendMessageReply.op:type_name -> common.OP
	3, // 4: chat.MessageToMQ.type:type_name -> common.PushType
	4, // 5: chat.MessageToMQ.sub:type_name -> common.Message
	5, // 6: chat.MessageToMQ.op:type_name -> common.OP
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_types_chat_proto_init() }
func file_types_chat_proto_init() {
	if File_types_chat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageToMQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_chat_proto_goTypes,
		DependencyIndexes: file_types_chat_proto_depIdxs,
		MessageInfos:      file_types_chat_proto_msgTypes,
	}.Build()
	File_types_chat_proto = out.File
	file_types_chat_proto_rawDesc = nil
	file_types_chat_proto_goTypes = nil
	file_types_chat_proto_depIdxs = nil
}
